version: "3.1"

services:
  matching_service:
    build: ./matching
    command: python server.py
    volumes:
      - ./matching:/app
    ports:
      - 3030:3030

  web_app:
    build: ./web
    command: npm start
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - 3333:3000
    depends_on:
      - matching_service
